services:
  # MySQL Database
  db:
    image: mysql:8.0
    container_name: drupal_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal_password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3308:3306"
    networks:
      - drupal_network

  # PHP-FPM
  php:
    build: ./app/php
    container_name: drupal_php
    restart: unless-stopped
    volumes:
      - ./src/drupal/web:/var/www/html
    depends_on:
      - db
    networks:
      - drupal_network

  # Nginx Web Server
  nginx:
    build: ./app/nginx
    container_name: drupal_nginx
    restart: unless-stopped
    ports:
      - "8082:80"
    volumes:
      - ./src/drupal/web:/var/www/html
    depends_on:
      - php
    networks:
      - drupal_network

  # phpMyAdmin
  phpmyadmin:
    build: ./app/phpmyadmin
    container_name: drupal_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_USER: drupal
      PMA_PASSWORD: drupal_password
    ports:
      - "8083:80"
    depends_on:
      - db
    networks:
      - drupal_network

volumes:
  db_data:

networks:
  drupal_network:
    driver: bridge
