FROM mysql:8.0

# Set environment variables
ENV MYSQL_ROOT_PASSWORD=rootpassword
ENV MYSQL_DATABASE=drupal
ENV MYSQL_USER=drupal
ENV MYSQL_PASSWORD=drupal_password

# Expose port 3306
EXPOSE 3306

# Start MySQL
CMD ["mysqld"]
