name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME || '' }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN || '' }}

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, json, xml, gd, zip, intl, bcmath
          tools: composer:v2

      - name: Get Composer cache directory
        id: composer-cache
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install Composer dependencies (no dev, prefer dist)
        run: |
          if [ -f "src/drupal/web/composer.json" ]; then pushd src/drupal/web; fi
          composer install --no-interaction --prefer-dist --no-progress
          if [ -f "composer.json" ] && [ -d vendor ]; then echo "Composer vendor installed"; fi
          if [ -f "composer.json" ] && [ -d vendor ]; then popd || true; fi

      - name: Validate Composer files (root if any)
        run: |
          if [ -f composer.json ]; then composer validate --no-check-publish; fi

      - name: Validate Drupal composer (src/drupal/web)
        run: |
          if [ -f src/drupal/web/composer.json ]; then (cd src/drupal/web && composer validate --no-check-publish); fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub (optional)
        if: ${{ env.DOCKERHUB_USERNAME != '' && env.DOCKERHUB_TOKEN != '' }}
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Build images
        run: |
          docker build -t ci-cd-drupal-demo-php:ci ./app/php
          docker build -t ci-cd-drupal-demo-nginx:ci ./app/nginx
          docker build -t ci-cd-drupal-demo-phpmyadmin:ci ./app/phpmyadmin || echo "phpmyadmin not present or build failed, continuing"

      - name: Push images (optional when logged in)
        if: ${{ env.DOCKERHUB_USERNAME != '' && env.DOCKERHUB_TOKEN != '' }}
        run: |
          docker tag ci-cd-drupal-demo-php:ci ${{ env.DOCKERHUB_USERNAME }}/ci-cd-drupal-demo-php:ci
          docker tag ci-cd-drupal-demo-nginx:ci ${{ env.DOCKERHUB_USERNAME }}/ci-cd-drupal-demo-nginx:ci
          docker push ${{ env.DOCKERHUB_USERNAME }}/ci-cd-drupal-demo-php:ci
          docker push ${{ env.DOCKERHUB_USERNAME }}/ci-cd-drupal-demo-nginx:ci

      - name: Archive project as artifact
        run: |
          zip -r project.zip . -x "**/.git/**"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: repo-archive
          path: project.zip

  deploy:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME || '' }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN || '' }}
      DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
      DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
      DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Ensure deploy path exists on server
        run: |
          ssh -o StrictHostKeyChecking=no ${DEPLOY_USER}@${DEPLOY_HOST} "mkdir -p ${DEPLOY_PATH}"

      - name: Rsync repo to server
        run: |
          rsync -az --delete -e "ssh -o StrictHostKeyChecking=no" ./ ${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_PATH}/

      - name: Login to Docker Hub on server (optional)
        if: ${{ env.DOCKERHUB_USERNAME != '' && env.DOCKERHUB_TOKEN != '' }}
        run: |
          ssh -o StrictHostKeyChecking=no ${DEPLOY_USER}@${DEPLOY_HOST} "echo '${DOCKERHUB_TOKEN}' | docker login -u '${DOCKERHUB_USERNAME}' --password-stdin"

      - name: Start/Update services
        run: |
          ssh -o StrictHostKeyChecking=no ${DEPLOY_USER}@${DEPLOY_HOST} "cd ${DEPLOY_PATH} && docker compose pull || true && docker compose up -d --build"

      - name: Run Drupal updates and clear caches
        run: |
          ssh -o StrictHostKeyChecking=no ${DEPLOY_USER}@${DEPLOY_HOST} "docker exec drupal_php sh -lc 'cd /var/www/html && if [ -x vendor/bin/drush ]; then vendor/bin/drush updb -y || true; vendor/bin/drush cr || true; fi'"


